projectType: extension
additionalTestConfigs:
  oracle_jdk8:
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Doracle -DminVersion=4.3.0 -DskipTita"
  postgresql_jdk8:
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dpostgresql -DminVersion=4.3.0 -DskipTita"
  mysql_jdk8:
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dmysql -DminVersion=4.3.0 -DskipTita"
  mssql_jdk8:
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dmssql -DminVersion=4.3.0 -DskipTita"
  derby_jdk8:
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dderby -DminVersion=4.3.0 -DskipTita"
    # In all jdk11 configurations, the runtime is set to 4.8.x until W-17842670 is fixed
    # Because of this, the discovery configuration is bypassed and we need to specify runtimeProduct as MULE_EE
  oracle_jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Doracle -DskipTita -DruntimeVersion=4.8.5 -DruntimeProduct=MULE_EE"
  postgresql_jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dpostgresql -DskipTita -DruntimeVersion=4.8.5"
  mysql_jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dmysql -DskipTita -DruntimeVersion=4.8.5"
  mssql_jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dmssql -DskipTita -DruntimeVersion=4.8.5"
  derby_jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -Dderby -DskipTita -DruntimeVersion=4.8.5"
  oracle_jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0 -Doracle -DskipTita"
  postgresql_jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0 -Dpostgresql -DskipTita"
  mysql_jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0 -Dmysql -DskipTita"
  mssql_jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0 -Dmssql -DskipTita"
  derby_jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: "-Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0 -Dderby -DskipTita"
