name: teradata-ci-code-coverage
on:
  workflow_dispatch:
  schedule:
  - cron: "0 6 * * *"
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  teradata-tests:
    name: "Run Mule Teradata Connector Unit Tests"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ vars.BRANCH_NAME }}
      - name: "Install Java 1.8"
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: "Install maven"
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
          tar -xvf apache-maven-3.9.9-bin.tar.gz
          sudo mv apache-maven-3.9.9 /opt/
          M2_HOME='/opt/apache-maven-3.9.9'
          export PATH="$M2_HOME/bin:$PATH"
      - name: "Run Unit Tests"
        run:  |  
          mvn clean install
